// Generated by https://quicktype.io

export interface PostsResponse {
  kind: string;
  nextPageToken?: string;
  items: Item[];
  etag: string;
}

export interface Item {
  kind: Kind;
  id: string;
  blog: Blog;
  published: string;
  updated: string;
  url: string;
  selfLink: string;
  title: string;
  content: string;
  author: Author;
  replies: Replies;
  labels?: string[];
  etag: string;
}

export interface Author {
  id: string;
  displayName: DisplayName;
  url: string;
  image: Image;
}

export enum DisplayName {
  Aio392 = 'Aio392',
}

export interface Image {
  url: string;
}

export interface Blog {
  id: string;
}

export enum Kind {
  BloggerPost = 'blogger#post',
}

export interface Replies {
  totalItems: string;
  selfLink: string;
}
